# Based on: http://www.enekoalonso.com/articles/creating-swift-frameworks-for-ios-osx-and-tvos
language: objective-c

os:
  - osx
osx_image: xcode8.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Tests/Tests.xcworkspace
  - IOS_SCHEME="iOS Tests"
  - IOS_SDK=iphonesimulator9.3
  - OSX_SCHEME="macOS Tests"
  - OSX_SDK=macosx10.11
  matrix:
    - DESTINATION="OS=9.0,name=iPhone 5S"      SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="OS=9.1,name=iPhone 5S"      SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 5S"      SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 5S"      SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="OS=10.0,name=iPhone 5S"     SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="OS=10.1,name=iPhone 5S"     SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="OS=10.2,name=iPhone 5S"     SCHEME="$IOS_SCHEME"    SDK="$IOS_SDK"    POD_LINT="NO"
    - DESTINATION="arch=x86_64"                SCHEME="$OSX_SCHEME"    SDK="$OSX_SDK"    POD_LINT="YES"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c;

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --private --verbose;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
