osx_image: xcode8.2
language: objective-c
script:
- set -o pipefail && xcodebuild test -workspace Tests/Tests.xcworkspace -scheme Tests -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint